# Generated by Django 2.2.13 on 2021-05-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210516_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick',
        ),
    ]
