# Generated by Django 2.2.13 on 2021-05-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20210514_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='categories.Category'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
