# Generated by Django 2.2.13 on 2021-05-17 06:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20210517_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
